using System.Runtime.Serialization;

namespace ServiceNow.Api.Example;

/// <summary>
/// This is a simple model class that represents the fields we are bringing back from the ServiceNow query in Program.cs.
/// </summary>
[DataContract]
public class WinServerModel
{
	/// <summary>
	/// The sys_id field is the unique identifier for each record in ServiceNow.  It is a 32-character string that is generated by ServiceNow when the record is created.  It is used to uniquely identify the record and is often used as a reference in other tables.
	/// </summary>
	[DataMember(Name = "sys_id")]
	public string Id { get; set; } = string.Empty;

	/// <summary>
	/// The name field is the name of the Windows Server.  It is a string that is entered by the user when the record is created or updated.  It is often used as a display field in lists and forms.
	/// </summary>
	[DataMember(Name = "name")]
	public string Name { get; set; } = string.Empty;
}
